name: Unit Test
on: [push]

jobs:
  setupJDK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

  katas:
    runs-on: ubuntu-latest
    needs: setupJDK
    strategy:
      matrix:
        katas: [supermarket, tennis]
    steps:
      - uses: actions/checkout@v1

      - name: Unit Test
        run: ./gradlew test
        working-directory: ./${{ matrix.katas }}
        continue-on-error: false

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0